language: node_js
node_js:
  - 'node' # use latest stable nodejs version
before_script:
  - sudo cp /etc/redis/redis.conf /etc/redis/redis.custom.conf
  - sudo chmod 755 /etc/redis/redis.custom.conf
  - sudo echo notify-keyspace-events \"Ex\" >> /etc/redis/redis.custom.conf
  - sudo redis-server /etc/redis/redis.custom.conf
script:
  - npm run coverage # jest test with coverage flag does coverage too
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
